/**
 * Error codes and error-related constants
 */

export const ERROR_CODES = {
  // Auth errors
  INVALID_CREDENTIALS: 'AUTH_001',
  TOKEN_EXPIRED: 'AUTH_002',
  TOKEN_INVALID: 'AUTH_003',
  UNAUTHORIZED: 'AUTH_004',
  FORBIDDEN: 'AUTH_005',
  USER_NOT_FOUND: 'AUTH_006',
  EMAIL_ALREADY_EXISTS: 'AUTH_007',
  PHONE_ALREADY_EXISTS: 'AUTH_008',
  WEAK_PASSWORD: 'AUTH_009',
  INVALID_EMAIL_FORMAT: 'AUTH_010',
  INVALID_PHONE_FORMAT: 'AUTH_011',

  // Validation errors
  VALIDATION_FAILED: 'VAL_001',
  INVALID_INPUT: 'VAL_002',
  MISSING_REQUIRED_FIELD: 'VAL_003',
  INVALID_ENUM_VALUE: 'VAL_004',

  // Resource errors
  NOT_FOUND: 'RES_001',
  ALREADY_EXISTS: 'RES_002',
  CONFLICT: 'RES_003',

  // Business logic errors
  INSUFFICIENT_STOCK: 'BUS_001',
  INVALID_ORDER_STATUS: 'BUS_002',
  INVALID_PAYMENT: 'BUS_003',
  COMMISSION_CALCULATION_FAILED: 'BUS_004',
  SELLER_NOT_APPROVED: 'BUS_005',
  APPOINTMENT_CONFLICT: 'BUS_006',

  // Database errors
  DATABASE_ERROR: 'DB_001',
  TRANSACTION_FAILED: 'DB_002',
  MIGRATION_FAILED: 'DB_003',

  // External service errors
  MAIL_SERVICE_ERROR: 'EXT_001',
  PAYMENT_GATEWAY_ERROR: 'EXT_002',
  STORAGE_SERVICE_ERROR: 'EXT_003',

  // System errors
  INTERNAL_SERVER_ERROR: 'SYS_001',
  SERVICE_UNAVAILABLE: 'SYS_002',
  RATE_LIMIT_EXCEEDED: 'SYS_003',
  REQUEST_TIMEOUT: 'SYS_004',
} as const;

export const HTTP_STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;
