param(
  [string]$OutputFile = "/etc/nginx/snippets/cloudflare-realip.conf"
)

$v4Url = "https://www.cloudflare.com/ips-v4"
$v6Url = "https://www.cloudflare.com/ips-v6"

try {
  $v4Ranges = (Invoke-WebRequest -Uri $v4Url -UseBasicParsing).Content -split "`n" |
    ForEach-Object { $_.Trim() } |
    Where-Object { $_ -ne "" }

  $v6Ranges = (Invoke-WebRequest -Uri $v6Url -UseBasicParsing).Content -split "`n" |
    ForEach-Object { $_.Trim() } |
    Where-Object { $_ -ne "" }
} catch {
  throw "Failed to fetch Cloudflare IP ranges: $($_.Exception.Message)"
}

$dir = Split-Path -Parent $OutputFile
if ($dir -and -not (Test-Path $dir)) {
  New-Item -ItemType Directory -Path $dir -Force | Out-Null
}

$lines = @(
  "# Generated by scripts/update-cloudflare-realip.ps1",
  "# Source: https://www.cloudflare.com/ips/",
  "real_ip_header CF-Connecting-IP;",
  "real_ip_recursive on;",
  ""
)

$lines += $v4Ranges | ForEach-Object { "set_real_ip_from $_;" }
$lines += $v6Ranges | ForEach-Object { "set_real_ip_from $_;" }

Set-Content -Path $OutputFile -Value $lines -Encoding UTF8
Write-Host "Wrote Cloudflare real_ip config to: $OutputFile"
