#!/usr/bin/env bash
set -euo pipefail

OUTPUT_FILE="${OUTPUT_FILE:-/etc/nginx/snippets/cloudflare-realip.conf}"
TMP_FILE="$(mktemp)"

fetch() {
  local url="$1"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$url"
    return
  fi
  if command -v wget >/dev/null 2>&1; then
    wget -qO- "$url"
    return
  fi
  echo "Neither curl nor wget is available."
  exit 1
}

v4_ranges="$(fetch https://www.cloudflare.com/ips-v4)"
v6_ranges="$(fetch https://www.cloudflare.com/ips-v6)"

mkdir -p "$(dirname "$OUTPUT_FILE")"

{
  echo "# Generated by scripts/update-cloudflare-realip.sh"
  echo "# Source: https://www.cloudflare.com/ips/"
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
  echo

  while IFS= read -r cidr; do
    [[ -z "$cidr" ]] && continue
    echo "set_real_ip_from $cidr;"
  done <<< "$v4_ranges"

  while IFS= read -r cidr; do
    [[ -z "$cidr" ]] && continue
    echo "set_real_ip_from $cidr;"
  done <<< "$v6_ranges"
} > "$TMP_FILE"

mv "$TMP_FILE" "$OUTPUT_FILE"
echo "Wrote Cloudflare real_ip config to: $OUTPUT_FILE"
